name: Run Tests and Linting

on:
  push:
    branches:
    - "**"
    paths-ignore:
    - .vscode/**
    - LICENSE
    - README.md

  # Enable the workflow to be run manually
  workflow_dispatch:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Run Tests
      run: npm run test

    - name: Run Linting
      run: npm run lint
